default:
  image: python:3.11
  tags:
    - village_help_portal
before_script:
  - pip intsall uv
  - uv sync

stages:
  - lint
  - format
  - type_check
  - security
  - test
  - coverage

lint:
  stage: lint
  script:
    - uv run ruff check .
    - uv run flake8 . || true
    - uv run pylint app.py || true
    - uv run vulture . || true
    - uv run pyupgrade --py311-plus app.py

format:
  stage: format
  script:
    - uv run ruff format --check .

type_check:
  stage: type_check
  script:
    - uv run ruff format --check

security:
  stage: security
  script:
    - pip install -r requirements.txt
    - pip install bandit semgrep pip-audit
    - bandit -r . || true
    - semgrep scan --config auto . || true
    - pip-audit || true

test:
  stage: test
  script:
    - pip install -r requirements.txt
    - pip install pytest
    - pytest || echo "No tests found"

coverage:
  stage: coverage
  script:
    - pip install -r requirements.txt
    - pip install pytest pytest-cov
    - pytest --cov=. --cov-report=xml --cov-fail-under=1 || true